import turtle

def turtleLetter(letter,tur):
    if letter=="box":
        tur.setheading(0)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)

    elif letter == "A":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        tur.setpos(40, 0)
        tur.right(180)
    elif letter == "B":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(20)
        tur.backward(20)
        tur.left(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        #tur.fd(20)
        tur.pu()
        tur.setpos(40,0)
        tur.right(180)
        
    elif letter == "C":
        tur.setheading(0)
        tur.pu()
        tur.right(90)
        tur.fd(10)
        tur.right(90)
        tur.fd(30)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
    elif letter == "D":
        tur.left(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(8)
        tur.right(40)
        tur.fd(4)
        tur.right(50)
        tur.fd(3)
        tur.right(40)
        tur.fd(4)
        tur.right(50)
        tur.fd(15)
    elif letter == "E":
        tur.setheading(0)
        tur.pd()
        tur.fd(50)
        tur.right(180)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
        tur.left(180)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
        #tur.right(180)
    elif letter == "F":
        #tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        tur.setpos(40,0)
        tur.right(180)
                  
    elif letter == "G":
        tur.setheading(0)
        tur.pu()
        tur.right(90)
        tur.fd(10)
        tur.right(90)
        tur.fd(30)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)
    		
    elif letter == "H":
        tur.left(90)
        tur.fd(15)
        tur.right(180)
        tur.fd(7.5)
        tur.right(90)
        tur.fd(9)
        tur.left(180)
        tur.right(90)
        tur.fd(5)
        tur.left(90)
        
        
    elif letter == "I":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(100)
    elif letter == "J":
        #tur.setheading(0)
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.left(180)
        tur.fd(40)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.circle(-15,180)
    
    elif letter == "K":
        tur.right(90)
        tur.fd(50)
        tur.left(180)
        tur.fd(30)
        tur.right(60)
        tur.fd(30)
        tur.left(180)
        tur.fd(30)
        tur.left(110)
        tur.fd(50)
    elif letter == "L":
        tur.setheading(0)
        tur.pu()
        tur.left(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(10)
    
                  
    elif letter == "M":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.left(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.pu()
        #fixes
        #tur.right(180
    elif letter == "N":
        tur.left(90)
        tur.fd(30)
        tur.right(140)
        tur.fd(40)
        tur.left(140)
        tur.fd(30)
        tur.pu()
        tur.setpos(40,0)
    elif letter == "O":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
    elif letter == "P":
        tur.left(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(15)
        tur.right(20)
        tur.fd(10)
        tur.left(30)
        tur.fd(10)
                  
    elif letter == "Q":
     
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.left(180)
        tur.fd(20)
        tur.right(45)
        tur.fd(15)
    elif letter == "R":
        tur.left(90)
        tur.fd(40)
        tur.circle(-15,320)
        tur.left(180)
        tur.fd(40)
        tur.pu()
        tur.setpos(40,0)
                  
    elif letter == "S":
        tur.setheading(0)
        tur.pd()
        tur.fd(50)
        tur.left(180)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
        tur.left(90)
        tur.pu()
    elif letter == "T":
        tur.right(90)
        tur.fd(10)
        tur.left(180)
        tur.fd(10)
                  
    elif letter == "U":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.pu()
        tur.fd(30)
        tur.right(180)

    elif letter == "V":
        tur.right(60)
        tur.fd(40)
        tur.left(120)
        tur.fd(40)
    elif letter == "W":
        tur.right(60)
        tur.forward(50)
        tur.left(130)
        tur.forward(30)
        tur.right(130)
        tur.forward(30)
        tur.left(130)
        tur.forward(50)
    elif letter == "X":
        tur.left(90)
        tur.fd(10)
        tur.right(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(5)
                  
    elif letter == "Y":
        tur.setheading(0)
        tur.pd()
        tur.right(45)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(360)
        tur.fd(30)
        #fixes
        #tur.right(180)
    elif letter == "Z":
        tur.fd(50)
        tur.right(140)
        tur.fd(50)
        tur.left(140)		
        
    elif letter == "Ax":
        # code here
        tur.forward(40)
		
    else:
        turtleLetter("box",tur)
	







window = turtle.Screen()
tur = turtle.Turtle()
tur.speed(1)
#turtleLetter("box",tur)
turtleLetter("H",tur)


window.exitonclick()



